name: Update Product Data

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:     # Ручной запуск
  push:
    branches: [ main ]

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl xlrd

      - name: Create data directory
        run: mkdir -p data

      - name: Download source files (replace with your actual file URLs)
        run: |
          # ЗАМЕНИТЕ ЭТИ URL НА РЕАЛЬНЫЕ ССЫЛКИ НА ВАШИ ФАЙЛЫ
          # curl -o Прайс.xlsx "URL_ВАШЕГО_ПРАЙСА"
          # curl -o наличие котлы.xlsx "URL_ВАШЕГО_ФАЙЛА_ОСТАТКОВ"
          echo "Здесь должна быть загрузка файлов"

      - name: Run processing script
        run: python scripts/process_data.py

      - name: Commit and push if data changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git add Сводная_таблица_котлы_*.xlsx
          git diff --staged --quiet || (git commit -m "Auto-update data [skip ci]" && git push)