name: Update Product Data

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:     # Ручной запуск
  push:
    branches: [ main ]

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl xlrd requests lxml beautifulsoup4 html5lib

      - name: Debug - Check network connectivity
        run: |
          echo "Проверяем доступность внешних ресурсов..."
          ping -c 3 b24.engpx.ru || echo "Ping тест не прошел"
          curl -I "https://b24.engpx.ru/~1PZm1" || echo "Прайс недоступен"
          curl -I "https://b24.engpx.ru/~8G8gh" || echo "Наличие недоступно"

      - name: Run processing script
        run: |
          echo "Запускаем скрипт обработки..."
          python scripts/process_data.py

      - name: Verify generated files
        run: |
          echo "Проверяем созданные файлы:"
          ls -la *.json *.xlsx 2>/dev/null || echo "Файлы не найдены"
          
          if [ -f "data.json" ]; then
            echo "data.json существует, проверяем содержимое:"
            head -n 5 data.json
            echo "..."
            tail -n 2 data.json
          else
            echo "❌ data.json не создан!"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Добавляем только нужные файлы
          git add data.json
          git add Сводная_таблица_котлы_*.xlsx 2>/dev/null || echo "Excel файлы не найдены"
          
          # Проверяем изменения
          git status
          
          # Коммитим и пушим если есть изменения
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update: данные обновлены из внешних источников [skip ci]"
            git push
            echo "✅ Изменения запушены"
          else
            echo "ℹ️ Изменений нет, пропускаем коммит"
          fi

      - name: Cleanup old files
        run: |
          # Удаляем старые Excel файлы (оставляем только последние 5)
          ls -t Сводная_таблица_котлы_*.xlsx 2>/dev/null | tail -n +6 | xargs rm -f 2>/dev/null || echo "Нет файлов для очистки"
          echo "Оставшиеся файлы:"
          ls -la *.xlsx 2>/dev/null || echo "Excel файлов нет"
